// OBJECT ORIENTED PROJGRAMMING
#include<iostream.h>
#include<conio.h>

void main(){
   clrscr();
// Theory related to OOP
// Classes => Basic templates for creating objects
// Objects => basic runtime entities
// Data Encapsultaion => Wraaping data and functions into single unit
// inheritance => Properties of classes inherited to another
// polymorphism => ability to make more than one form

/* Opps
 1. Better code reusability using objects.
 2. simply create multiple methods in multiple classes.
 3. Principal Data hiding helps build secure system.
 4. multiple objects can C-exists without any interference.
 5. Emphasis is on Data rather than procedure.
*/
   getch();
}